/**
 * Coarse OSM shop/amenity (and related) type → BitbyBit taxonomy key.
 *
 * NSI brands carry a primary OSM tag. Unmapped types return null so a brand is
 * never filed under a guess — classify / Review still get the row.
 */

export type OsmCategory = {
  categoryKey: string;
  tag?: string;
};

const OSM_TO_CATEGORY: Record<string, OsmCategory> = {
  "shop=supermarket": { categoryKey: "groceries", tag: "Groceries" },
  "shop=greengrocer": { categoryKey: "groceries", tag: "Groceries" },
  "shop=butcher": { categoryKey: "groceries", tag: "Groceries" },
  "shop=bakery": { categoryKey: "groceries", tag: "Groceries" },
  "shop=pastry": { categoryKey: "groceries", tag: "Groceries" },
  "shop=seafood": { categoryKey: "groceries", tag: "Groceries" },
  "shop=cheese": { categoryKey: "groceries", tag: "Groceries" },
  "shop=dairy": { categoryKey: "groceries", tag: "Groceries" },
  "shop=wholesale": { categoryKey: "groceries", tag: "Groceries" },
  "shop=convenience": { categoryKey: "shopping", tag: "Convenience Stores" },
  "shop=alcohol": { categoryKey: "eating-out", tag: "Alcohol" },
  "shop=beverages": { categoryKey: "eating-out", tag: "Alcohol" },
  "shop=wine": { categoryKey: "eating-out", tag: "Alcohol" },
  "amenity=fast_food": { categoryKey: "eating-out", tag: "Fast Food" },
  "amenity=restaurant": { categoryKey: "eating-out", tag: "Restaurant" },
  "amenity=cafe": { categoryKey: "eating-out", tag: "Coffee" },
  "amenity=ice_cream": { categoryKey: "eating-out", tag: "Other Food & Drink" },
  "amenity=food_court": { categoryKey: "eating-out", tag: "Takeaway" },
  "amenity=bar": { categoryKey: "eating-out", tag: "Alcohol" },
  "amenity=pub": { categoryKey: "eating-out", tag: "Alcohol" },
  "amenity=biergarten": { categoryKey: "eating-out", tag: "Alcohol" },
  "amenity=fuel": { categoryKey: "car", tag: "Fuel" },
  "amenity=charging_station": { categoryKey: "getting-around", tag: "EV Charging" },
  "shop=car": { categoryKey: "car", tag: "Automotive" },
  "shop=car_repair": { categoryKey: "car", tag: "Servicing" },
  "shop=car_parts": { categoryKey: "car", tag: "Automotive" },
  "shop=tyres": { categoryKey: "car", tag: "Servicing" },
  "amenity=car_wash": { categoryKey: "car", tag: "Servicing" },
  "amenity=parking": { categoryKey: "getting-around", tag: "Parking" },
  "amenity=bicycle_rental": { categoryKey: "getting-around", tag: "Bikes & Scooters" },
  "shop=bicycle": { categoryKey: "getting-around", tag: "Bikes & Scooters" },
  "amenity=ferry_terminal": { categoryKey: "getting-around", tag: "Public Transport" },
  "amenity=bus_station": { categoryKey: "getting-around", tag: "Public Transport" },
  "amenity=taxi": { categoryKey: "getting-around", tag: "Taxis & Ride Shares" },
  "shop=doityourself": { categoryKey: "home-garden", tag: "Hardware" },
  "shop=hardware": { categoryKey: "home-garden", tag: "Hardware" },
  "shop=trade": { categoryKey: "home-garden", tag: "Hardware" },
  "shop=furniture": { categoryKey: "home-garden", tag: "Furniture" },
  "shop=bed": { categoryKey: "home-garden", tag: "Furniture" },
  "shop=houseware": { categoryKey: "home-garden", tag: "Home Improvement" },
  "shop=household_linen": { categoryKey: "home-garden", tag: "Home Improvement" },
  "shop=kitchen": { categoryKey: "home-garden", tag: "Home Improvement" },
  "shop=tiles": { categoryKey: "home-garden", tag: "Hardware" },
  "shop=flooring": { categoryKey: "home-garden", tag: "Hardware" },
  "shop=carpet": { categoryKey: "home-garden", tag: "Hardware" },
  "shop=paint": { categoryKey: "home-garden", tag: "Hardware" },
  "shop=lighting": { categoryKey: "home-garden", tag: "Home Improvement" },
  "shop=electrical": { categoryKey: "home-garden", tag: "Hardware" },
  "shop=garden_centre": { categoryKey: "home-garden", tag: "Home Improvement" },
  "shop=agrarian": { categoryKey: "home-garden", tag: "Hardware" },
  "shop=bbq": { categoryKey: "home-garden", tag: "Home Improvement" },
  "shop=department_store": { categoryKey: "shopping", tag: "Department Stores" },
  "shop=variety_store": { categoryKey: "shopping", tag: "Department Stores" },
  "shop=mall": { categoryKey: "shopping", tag: "Department Stores" },
  "shop=clothes": { categoryKey: "shopping", tag: "Clothing" },
  "shop=fashion_accessories": { categoryKey: "shopping", tag: "Clothing & Accessories" },
  "shop=shoes": { categoryKey: "shopping", tag: "Clothing & Accessories" },
  "shop=bag": { categoryKey: "shopping", tag: "Clothing & Accessories" },
  "shop=jewelry": { categoryKey: "shopping", tag: "Clothing & Accessories" },
  "shop=boutique": { categoryKey: "shopping", tag: "Clothing" },
  "shop=electronics": { categoryKey: "shopping", tag: "Electronics" },
  "shop=computer": { categoryKey: "shopping", tag: "Electronics" },
  "shop=mobile_phone": { categoryKey: "internet-phone", tag: "Mobile" },
  "shop=mobile_phone_accessories": { categoryKey: "shopping", tag: "Electronics" },
  "shop=hifi": { categoryKey: "shopping", tag: "Electronics" },
  "shop=appliance": { categoryKey: "shopping", tag: "Electronics" },
  "shop=vacuum_cleaner": { categoryKey: "shopping", tag: "Electronics" },
  "shop=stationery": { categoryKey: "shopping", tag: "Office Supplies" },
  "shop=copyshop": { categoryKey: "shopping", tag: "Office Supplies" },
  "shop=books": { categoryKey: "shopping", tag: "Books & News" },
  "shop=newsagent": { categoryKey: "shopping", tag: "Books & News" },
  "shop=gift": { categoryKey: "shopping", tag: "Gifts" },
  "shop=toys": { categoryKey: "shopping", tag: "Hobbies" },
  "shop=games": { categoryKey: "entertainment", tag: "Gaming" },
  "shop=video_games": { categoryKey: "entertainment", tag: "Video Games" },
  "shop=sports": { categoryKey: "shopping", tag: "Sporting Goods" },
  "shop=outdoor": { categoryKey: "shopping", tag: "Sporting Goods" },
  "shop=craft": { categoryKey: "shopping", tag: "Hobbies" },
  "shop=fabric": { categoryKey: "shopping", tag: "Hobbies" },
  "shop=art": { categoryKey: "shopping", tag: "Hobbies" },
  "shop=second_hand": { categoryKey: "shopping", tag: "Other Merchandise" },
  "shop=charity": { categoryKey: "donations", tag: "Charity" },
  "shop=pawnbroker": { categoryKey: "shopping", tag: "Other Merchandise" },
  "shop=tobacco": { categoryKey: "shopping", tag: "Tobacco & Vape" },
  "shop=e-cigarette": { categoryKey: "shopping", tag: "Tobacco & Vape" },
  "shop=chocolate": { categoryKey: "shopping", tag: "Other Merchandise" },
  "shop=tea": { categoryKey: "eating-out", tag: "Coffee" },
  "shop=coffee": { categoryKey: "eating-out", tag: "Coffee" },
  "shop=baby_goods": { categoryKey: "shopping", tag: "Other Merchandise" },
  "shop=cosmetics": { categoryKey: "personal-care", tag: "Hair & Beauty" },
  "shop=beauty": { categoryKey: "personal-care", tag: "Hair & Beauty" },
  "shop=hairdresser": { categoryKey: "personal-care", tag: "Hair & Beauty" },
  "shop=hairdresser_supply": { categoryKey: "personal-care", tag: "Hair & Beauty" },
  "shop=chemist": { categoryKey: "medical", tag: "Pharmacy" },
  "shop=optician": { categoryKey: "medical", tag: "Optical" },
  "shop=hearing_aids": { categoryKey: "medical", tag: "Other Medical" },
  "shop=medical_supply": { categoryKey: "medical", tag: "Other Medical" },
  "shop=nutrition_supplements": { categoryKey: "medical", tag: "Pharmacies & Supplements" },
  "shop=herbalist": { categoryKey: "medical", tag: "Pharmacies & Supplements" },
  "shop=pet": { categoryKey: "pets", tag: "Pet Supplies" },
  "shop=pet_grooming": { categoryKey: "pets", tag: "Pet Supplies" },
  "shop=florist": { categoryKey: "shopping", tag: "Gifts" },
  "shop=candles": { categoryKey: "shopping", tag: "Homewares" },
  "shop=boat": { categoryKey: "shopping", tag: "Sporting Goods" },
  "shop=ticket": { categoryKey: "entertainment", tag: "Events" },
  "shop=travel_agency": { categoryKey: "travel", tag: "Other Travel" },
  "amenity=pharmacy": { categoryKey: "medical", tag: "Pharmacy" },
  "amenity=hospital": { categoryKey: "medical", tag: "Other Medical" },
  "amenity=clinic": { categoryKey: "medical", tag: "GP & Specialists" },
  "amenity=doctors": { categoryKey: "medical", tag: "GP & Specialists" },
  "amenity=dentist": { categoryKey: "medical", tag: "Dental" },
  "healthcare=sample_collection": { categoryKey: "medical", tag: "Other Medical" },
  "healthcare=audiologist": { categoryKey: "medical", tag: "Other Medical" },
  "healthcare=blood_donation": { categoryKey: "donations", tag: "Charity" },
  "healthcare=counselling": { categoryKey: "personal-care", tag: "Other Personal Care" },
  "amenity=veterinary": { categoryKey: "pets", tag: "Veterinary Services" },
  "office=insurance": { categoryKey: "insurance", tag: "Insurance" },
  "office=telecommunication": { categoryKey: "internet-phone", tag: "Internet" },
  "office=tax_advisor": { categoryKey: "government-tax", tag: "Tax Payment" },
  "office=government": { categoryKey: "government-tax", tag: "Government Services" },
  "office=lawyer": { categoryKey: "bank-fees", tag: "Professional Fees" },
  "office=mortgage": { categoryKey: "rent-mortgage", tag: "Mortgage Payment" },
  "leisure=fitness_centre": { categoryKey: "personal-care", tag: "Gyms & Fitness" },
  "leisure=sports_centre": { categoryKey: "personal-care", tag: "Fitness" },
  "leisure=bowling_alley": { categoryKey: "entertainment", tag: "Events & Amusement" },
  "leisure=trampoline_park": { categoryKey: "entertainment", tag: "Events & Amusement" },
  "leisure=playground": { categoryKey: "entertainment", tag: "Events & Amusement" },
  "leisure=indoor_play": { categoryKey: "entertainment", tag: "Events & Amusement" },
  "leisure=escape_game": { categoryKey: "entertainment", tag: "Events & Amusement" },
  "leisure=amusement_arcade": { categoryKey: "entertainment", tag: "Gaming" },
  "leisure=miniature_golf": { categoryKey: "entertainment", tag: "Events & Amusement" },
  "amenity=cinema": { categoryKey: "entertainment", tag: "TV & Movies" },
  "amenity=theatre": { categoryKey: "entertainment", tag: "Events" },
  "amenity=casino": { categoryKey: "entertainment", tag: "Casinos & Gambling" },
  "amenity=nightclub": { categoryKey: "entertainment", tag: "Events" },
  "tourism=hotel": { categoryKey: "travel", tag: "Hotels" },
  "tourism=motel": { categoryKey: "travel", tag: "Hotels" },
  "tourism=hostel": { categoryKey: "travel", tag: "Accommodation" },
  "tourism=guest_house": { categoryKey: "travel", tag: "Accommodation" },
  "tourism=caravan_site": { categoryKey: "travel", tag: "Accommodation" },
  "tourism=theme_park": { categoryKey: "entertainment", tag: "Events & Amusement" },
  "amenity=car_rental": { categoryKey: "travel", tag: "Rental Cars" },
  "amenity=bureau_de_change": { categoryKey: "bank-fees", tag: "Foreign Transaction Fees" },
  "amenity=school": { categoryKey: "education-childcare", tag: "Education" },
  "amenity=college": { categoryKey: "education-childcare", tag: "Education" },
  "amenity=university": { categoryKey: "education-childcare", tag: "Education" },
  "amenity=kindergarten": { categoryKey: "education-childcare", tag: "Childcare" },
  "amenity=childcare": { categoryKey: "education-childcare", tag: "Childcare" },
  "amenity=prep_school": { categoryKey: "education-childcare", tag: "Education" },
  "amenity=music_school": { categoryKey: "education-childcare", tag: "Education" },
  "amenity=recycling": { categoryKey: "utilities", tag: "Sewage & Waste" },
};

export function osmTypeToCategory(osm: string | undefined): OsmCategory | null {
  if (!osm) return null;
  const key = osm.trim().toLowerCase();
  return OSM_TO_CATEGORY[key] ?? null;
}
